ourjson:
  image: musedlab/ha-ourjson:beta
  restart: always
  environment:
    - MONGO_DB_NAME=ourjson
    - VIRTUAL_HOST=api.beta.musedlab.org
  expose:
    - "8080"
  external_links:
    - mongo/mongo-cluster:mongo
