ourjson:
  image: musedlab/ha-ourjson:beta
  restart: always
  environment:
    - MONGO_DB_NAME=ourjson
    - VIRTUAL_HOST=api.beta.musedlab.org
  expose:
    - "8080"
  external_links:
    - mongo/mongo-cluster:mongo
api:
  ports:
  - 443:8080
  - 80:8080
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.loadbalancer.ssl.ports: '443'
  links:
    - ourjson:ourjson
  tty: true
  image: rancher/load-balancer-service
  stdin_open: true
